version: '3.7'

services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=challengedb
      - POSTGRES_USER=fiap
      - POSTGRES_PASSWORD=fiap
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - burgerstore_network
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    environment:
      - POSTGRES_DB=challengedb
      - POSTGRES_USER=fiap
      - POSTGRES_PASSWORD=fiap
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "8000:8000"
    restart: always
    networks:
      - burgerstore_network
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data:
 # web_data:

networks:
  burgerstore_network:
    driver: bridge