version: '3.7'

services:
  db:
    image: postgres:12.15
    container_name: db
    environment:
      - POSTGRES_DB=challengedb
      - POSTGRES_USER=fiap
      - POSTGRES_PASSWORD=fiap
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data:
