version: '3.7'

services:
  orderdb:
    image: postgres
    container_name: orderdb
    environment:
      - POSTGRES_DB=orderdb
      - POSTGRES_USER=fiap
      - POSTGRES_PASSWORD=fiap
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - project-network

  order-app:
    #build: .
    image: deboraferrarids2/challenge_web:v2.0
    container_name: order-app
    volumes:
      - .:/usr/src/app
      - ./logs:/usr/src/app/logs
    ports:
      - "8080:8080"
    depends_on:
      - orderdb
    networks:
      - project-network
    restart: always
    command: bash -c "sleep 10 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8080" 

volumes:
  data:

networks:
  project-network:
    driver: bridge
    ipam:
      driver: default