apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-dep
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: challenge
  template:
    metadata:
      labels:
        app: challenge
    spec:
      containers:
        - name: postgres-container
          image: thiago5gg/postgres-challenge
          env:
            - name: POSTGRES_DB
              value: challengedb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
          ports:
            - containerPort: 5432
        - name: challenge-container
          image: thiago5gg/challenge-k
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-key
          ports:
            - containerPort: 5000
